""" Autogeneration handling module """

import api

def get_instance_number(token, pid):
    """ 
        Maps the token to an instance number for a prolem.

        Args:
            token: the unique token to map
            pid: the problem id
        Returns:
            The instance number
    """
    return token


def get_problem_instance(problem, tid):
    """ 
        Returns an instance of the autogenerated problem.

        Args:
            problem: the problem object
            tid: the tid
        Returns:
            An instance of the problem object.
    """
    return problem
