"""
Autogenerated Problem Facilitation
"""

import api

from os import path
from string import Template

from api.common import InternalException

log = api.logger.use(__name__)

def replace_source_tokens(file_path, lookup, out_path):
    """
    Replace tokens in a file and write out the substitution.

    Args:
        file_path: the path of the file to be read.
        lookup: a dictionary containing the substitutions.
        out_path: file in which the substitutions will be written.
    """

    if not path.isfile(file_path):
        raise InternalException("File: {} does not exist.".format(file_path))

    try:
        source_file = open(file_path, "r")
        source = source_file.read()
    except Exception:
        raise InternalException("Unable to read from source file.")

    template = Template(source)

    output = template.safe_substitute(lookup)

    try:
        output_file = open(out_path, "w")
        output_file.write(output)
    except Exception:
        raise InternalException("Unable to write to output file.")
