#!/bin/bash

# Transpile the CoffeeScript files
echo "Transpiling Coffeescript"
coffee -c -o /home/vagrant/web/js/ /home/vagrant/web/coffee/

# Shutdown the server
echo "Shutting down nginx"
sudo service nginx stop

# Clean out the old files
echo "Cleaning up old files"
sudo rm -rf /srv/http/ctf/*

echo "Generating web with Jekyll"
cd /home/vagrant/web
sudo jekyll build

echo "Copying files to server"
#sudo cp -r /home/vagrant/web/* /srv/http/ctf/
sudo cp -r /home/vagrant/problem_static /srv/http/ctf/problem-static

# Make sure everything is in UNIX format.
sudo dos2unix -q /srv/http/ctf/*.html

# Start the server
echo "Restarting the server"
sudo service nginx start

# Clear the cache
echo "Clearing the API cache"
/home/vagrant/api/api_manager.py database clear cache

#Start picoCTF API
echo "Starting the picoCTF API"
tmux kill-session -t picoapi 2> /dev/null
tmux new-session -s picoapi -d "cd /home/vagrant/api && python3 run.py"
