#!/bin/bash

# Transpile the CoffeeScript files
echo "Transpiling Coffeescript"
coffee -c -o /home/vagrant/web/js/ /home/vagrant/web/coffee/

# Run minigames devploy (this should be removed for release)
#/home/vagrant/minigames/scripts/ipf-devploy

# Shutdown the server
echo "Shutting down nginx"
sudo service nginx stop

# Clean out the old files
echo "Cleaning up old files"
sudo rm -rf /srv/http/ctf/*

# Copy files to the server
sudo chmod a+w /home/vagrant/web *
dos2unix /home/vagrant/web/*.html > /dev/null 2>&1
echo "Building site with Jekyll"
cd /home/vagrant/web
cp /home/vagrant/game/game.html .
# Block writing to copied in HTML to avoid mistakes
sudo chmod a-w game.html
sudo chmod -R a-w /home/vagrant/webex/web/*
cp -p -r /home/vagrant/webex/web/* .
sudo chmod -R a+w /home/vagrant/webex/web/*
sudo jekyll build
cd -

echo "Copying files to server"
sudo cp -r /home/vagrant/webex/img/* /srv/http/ctf/img
sudo cp -r /home/vagrant/webex/css/* /srv/http/ctf/css
sudo cp -r /home/vagrant/minigames /srv/http/ctf
sudo cp -r /home/vagrant/game /srv/http/ctf
sudo mv /srv/http/ctf/game.html /srv/http/ctf/game/index.html

# Start the server
echo "Restarting the server"
sudo service nginx start

#Start picoCTF API
echo "Starting the picoCTF API"
tmux kill-session -t picoapi 2> /dev/null
tmux new-session -s picoapi -d "cd /home/vagrant/api && python3 run.py"
